import type { Project } from '@/types';

export const PROJECTS: Project[] = [
  {
    id: 1,
    titleKey: 'projects.items.projectOne.title',
    descriptionKey: 'projects.items.projectOne.description',
    tags: ['#Minecraft', '#JavaScript', '#GraalJS', '#Java21', '#Implement'],
    featured: true,
    gradient: 'from-blue-500/20 to-purple-500/20',
    github: 'https://github.com/trethore/MQS',
  },
  {
    id: 2,
    titleKey: 'projects.items.projectTwo.title',
    descriptionKey: 'projects.items.projectTwo.description',
    tags: ['#Rust', '#LLMs', '#Fuzzy', '#Patch', '#Optimize'],
    featured: false,
    gradient: 'from-emerald-500/20 to-teal-500/20',
    github: '#',
  },
  {
    id: 3,
    titleKey: 'projects.items.projectThree.title',
    descriptionKey: 'projects.items.projectThree.description',
    tags: ['#Crypto', '#Market', '#NestJs', '#TailwindCSS', '#Prisma', '#GraphQL', '#Administer'],
    featured: true,
    gradient: 'from-orange-500/20 to-red-500/20',
    github: '#',
  },
  {
    id: 4,
    titleKey: 'projects.items.projectFour.title',
    descriptionKey: 'projects.items.projectFour.description',
    tags: ['#gerer', '#NextJS', '#React', '#TypeScript', '#TailwindCSS', '#next-intl', '#RadixUI', '#GSAP'],
    featured: false,
    gradient: 'from-pink-500/20 to-rose-500/20',
    github: 'https://github.com/trethore/trethore.github.io',
  },
  {
    id: 5,
    titleKey: 'projects.items.projectFive.title',
    descriptionKey: 'projects.items.projectFive.description',
    tags: ['#Crypto', '#Rust', '#TUI', '#Kraken', '#OHLCVT', '#DataCleaning', '#Analysis', '#CLI', '#Conduire'],
    featured: false,
    gradient: 'from-violet-500/20 to-indigo-500/20',
    github: '#',
  },
  {
    id: 6,
    titleKey: 'projects.items.projectSix.title',
    descriptionKey: 'projects.items.projectSix.description',
    tags: ['#Python', '#MachineLearning', '#PostgreSQL', '#RecommendationSystem', '#Optimization', '#DataScience', '#SpotifyDataset', '#Scikit-learn', '#Collaborate'],
    featured: false,
    gradient: 'from-cyan-500/20 to-blue-500/20',
    github: '#',
  },
];
