import type { Project } from '@/types';

export const PROJECTS: Project[] = [
  {
    id: 1,
    title: 'Project One',
    description: 'A cutting-edge web application with modern features',
    tags: ['React', 'Next.js', 'TypeScript'],
    featured: true,
    gradient: 'from-blue-500/20 to-purple-500/20',
    github: '#',
    demo: '#',
  },
  {
    id: 2,
    title: 'Project Two',
    description: 'An innovative mobile-first platform',
    tags: ['React Native', 'Firebase', 'Redux'],
    featured: false,
    gradient: 'from-emerald-500/20 to-teal-500/20',
    github: '#',
    demo: '#',
  },
  {
    id: 3,
    title: 'Project Three',
    description: 'Full-stack e-commerce solution',
    tags: ['Node.js', 'PostgreSQL', 'Stripe'],
    featured: true,
    gradient: 'from-orange-500/20 to-red-500/20',
    github: '#',
    demo: '#',
  },
  {
    id: 4,
    title: 'Project Four',
    description: 'Real-time collaboration tool',
    tags: ['WebSockets', 'Express', 'MongoDB'],
    featured: false,
    gradient: 'from-pink-500/20 to-rose-500/20',
    github: '#',
    demo: '#',
  },
  {
    id: 5,
    title: 'Project Five',
    description: 'AI-powered analytics dashboard',
    tags: ['Python', 'TensorFlow', 'React'],
    featured: false,
    gradient: 'from-violet-500/20 to-indigo-500/20',
    github: '#',
    demo: '#',
  },
  {
    id: 6,
    title: 'Project Six',
    description: 'Beautiful design system and component library',
    tags: ['Tailwind', 'Storybook', 'Figma'],
    featured: false,
    gradient: 'from-cyan-500/20 to-blue-500/20',
    github: '#',
    demo: '#',
  },
];
